name: Plan Terraform changes
on:
  workflow_call:
    inputs:
      concurrency_group:
        required: false
        type: string
        default: 'create-plan-${{ github.ref }}'
      run_name:
        required: false
        type: string
        default: 'Plan Terraform changes - ${{ github.ref }}'
      environment:
        required: true
        type: string
      gcp_sa_email:
        required: true
        type: string
      gcp_wif_resource_id:
        required: true
        type: string

concurrency:
  group: ${{ inputs.concurrency_group }}
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    env:
      ENVIRONMENT: ${{ inputs.environment }}
    name: Plan Terraform changes
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Bootstrap repository
        uses: ./.github/actions/bootstrap-repository
      - name: Login to GCP
        uses: google-github-actions/auth@v3
        id: gcp_auth
        with:
          export_environment_variables: 'true'
          workload_identity_provider: ${{ inputs.gcp_wif_resource_id }}
          service_account: ${{ inputs.gcp_sa_email }}
          token_format: 'id_token'
          id_token_audience: '//iam.googleapis.com/projects/1019265211616/locations/global/workloadIdentityPools/terraform-cloud/providers/terraform-cloud'
          id_token_include_email: 'true'
      - name: Retrieve TF Cloud credentials
        uses: ./.github/actions/terraform-cloud-login
        id: tf_cloud_login
      - name: Run Terraform plan
        uses: ./.github/actions/terraform-plan
        id: plan
        with:
          environment: ${{ inputs.environment }}
          oidc_token: ${{ steps.gcp_auth.outputs.id_token }}
          tf_api_token: ${{ steps.tf_cloud_login.outputs.terraform_cloud_api_token }}
        env:
          TF_TOKEN_app_terraform_io: ${{ steps.tf_cloud_login.outputs.terraform_cloud_api_token }}
